FROM node:16-alpine 

WORKDIR /my-project

COPY package.json  ./

RUN yarn install --frozen-lockfile

RUN yarn add @emotion/react@^11 @emotion/styled@^11.8.1 framer-motion@^4 

COPY . .

EXPOSE 3000

CMD ["yarn", "start"]