FROM node:16-alpine AS dependeces

WORKDIR /build

COPY package.json ./

COPY yarn.lock ./

RUN yarn install

COPY . .

RUN yarn nx build api


ENV PORT=3000

ENV NODE_ENV=production

WORKDIR /usr/src/app

COPY --from=dependeces /build/dist/apps/api .

COPY --from=dependeces /build/node_modules node_modules 

EXPOSE ${PORT}

CMD ["yarn", "start"]

