FROM node:16-alpine

WORKDIR /usr/src/app

COPY package.json ./

RUN yarn install

RUN rm -r node_modules/@next/swc-linux-x64-gnu

COPY . .

RUN ls -al

RUN yarn nx build admin --skip-nx-cache

ENV PORT=3000

RUN ls -al

EXPOSE ${PORT}

CMD ["./node_modules/.bin/nx" , "serve" , "admin"]

