FROM node:16-alpine

WORKDIR /build

COPY package.json ./

COPY yarn.lock ./

RUN yarn install

RUN rm -r node_modules/@next/swc-linux-x64-gnu

COPY . .

RUN ls -al

RUN npm install -g @nrwl/cli

RUN nx build admin 

RUN ls ./dist

ENV PORT=3000

ENV NODE_ENV=production

RUN ls -al

EXPOSE ${PORT}

CMD ["nx" , "serve" , "admin"]

