name: Nx wellness Application
on:
  push:
    branches: [develop, main]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using key
        uses: fifsky/ssh-action@master
        with:
          command: whoami
          host: ${{ secrets.HOST_SSH_DOKKU }}
          user: ${{ secrets.USER_SSH_DOKKU }}
          key: ${{ secrets.SECRET_SSH }}
