name: Nx wellness Application
on:
  push:
    branches: [develop]

jobs:
  setup:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Node.js, NPM and yarn
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            .yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependeces
        run: yarn
      - name: dokku sample
        run: dokku --help
